version: "3"
services:
  # Server
  server:
    build: ./server
    expose:
      - ${APP_SERVER_PORT}
    envionment:
      API_HOST: ${API_HOST}
      APP_SERVER_PORT: ${APP_SERVER_PORT}
    ports:
      - ${APP_SERVER_PORT}:${APP_SERVER_PORT}
    volumes:
      - ./server:/home/alex_chen/server
    command: npm run api-server

  # Client
  client:
    build: ./client
    environment:
      - REACT_APP_PORT=${REACT_PORT}
    expose:
      - ${REACT_APP_PORT}
    ports:
      - ${REACT_APP_PORT}:${REACT_APP_PORT}
    volumes:
      - ./client/public:/usr/share/nginx/html
    links:
      - server
    command: nginx -g daemon off;
